config/routes.rb
#require ‘sidekiq/web’

YourPriorities::Application.routes.draw do
  match '/donations/thank_you' => 'donations#thank_you'
  match '/donations/estartup' => 'donations#estartup'
  match '/donations/status' => 'donations#status'
  match '/donations/thank_you_estartup' => 'donations#thank_you_estartup'

 # mount Sidekiq::Web, at: ‘/sidekiq’

  resources :donations

  resources :subscriptions
  resources :plans
  resources :pages
  #mount Resque::Server.new, :at => '/resque' if Rails.env.production?

  mount Tolk::Engine => '/tolk', :as => 'tolk'

  devise_for :users, controllers: {
    sessions: "sessions",
    invitations:"users/invitations",
    registrations: "registrations",
    passwords: "passwords",
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  #mount Monologue::Engine, at: '/blog'

  resources :categories

  match '/groups/suggest_user' => 'groups#suggest_user'

  match '/users/eula' => 'users#eula'

  match "/about/rules" => redirect("/pages/2")
  match "/about/faq" => redirect("/pages/2")

  match '/ideas/flag/:id' => 'ideas#flag'
  match '/ideas/abusive/:id' => 'ideas#abusive'
  match '/ideas/not_abusive/:id' => 'ideas#not_abusive'
  match '/admin/all_flagged' => 'admin#all_flagged'
  match '/admin/statistics' => 'admin#statistics'
  match '/admin/all_deleted' => 'admin#all_deleted'
  match '/users/list_suspended' => 'users#list_suspended'
  match '/users/additional_information' => 'users#additional_information'
  match '/users/destroy_from_admin' => 'users#destroy_from_admin'

  match '/subscription_accounts/select_plan' => 'subscription_accounts#select_plan'
  match 'authenticate_from_island_is' =>'users#authenticate_from_island_is'
  match '/sub_instances/setup_status' =>'sub_instances#setup_status'

  resources :subscription_accounts do
    collection do
      get :users
      get :about
    end
  end

  resources :groups

  resources :sub_instances do
    member do
      get :email
      get :picture
      put :picture_save
    end
  end

  resources :users do
  	resource :profile
  	collection do
  	  get :endorsements
  	  post :order
  	end
  	member do
  	  put :suspend
      put :unsuspend
      get :activities
      get :comments
  	  get :points
  	  get :discussions
  	  get :capital
  	  put :impersonate
  	  get :followers
  	  get :documents
  	  get :stratml
  	  get :ignorers
  	  get :following
  	  get :ignoring
  	  post :follow
  	  post :unfollow
  	  get :make_admin
      get :unmake_admin
  	  get :ads
  	  get :ideas
  	  get :signups
  	  post :endorse
  	  get :resend_activation
    end
    resources :messages
    resources :followings do
      collection do
        put :multiple
      end
    end
    resources :user_contacts, :as => "contacts" do
      collection do
        put :multiple
        get :following
        get :members
        get :not_invited
        get :invited
      end
    end
  end

  resources :settings do
    collection do
      get :signups
      get :picture
      put :picture_save
      get :legislators
      post :legislators_save
      get :delete
    end
  end

  resources :ideas do
  	member do
      get :statistics
      put :flag_inappropriate
      get :flag
      put :bury
      put :compromised
      put :successful
      put :failed
      put :intheworks
      post :endorse
      get :endorsed
      get :opposed
      get :activities
      get :endorsers
      get :opposers
      get :discussions
      put :create_short_url
      post :tag
      put :tag_save
      get :points
      get :opposer_points
      get :endorser_points
      get :neutral_points
      get :everyone_points
      get :top_points
      get :idea_detail
      get :endorsed_points
      get :opposed_top_points
      get :endorsed_top_points
      get :comments
      get :documents
      get :update_status
      get :move
      post :move
      get :change_category
      put :change_category
  	end
  	collection do
      get :yours
      get :yours_finished
      get :yours_top
      get :yours_ads
      get :yours_lowest
      get :yours_created
      get :network
      get :consider
      get :finished
      get :finished_in_progress
      get :finished_successful
      get :finished_failed
      get :finished_compromised
      get :ads
      get :top
      get :by_tag
      get :by_impressions
      get :most_discussed
      get :all_tags
      get :top_24hr
      get :top_7days
      get :top_30days
      get :rising
      get :falling
      get :controversial
      get :random
      get :newest
      get :untagged
      get :revised
  	end
    resources :changes do
      member do
        put :start
        put :stop
        put :approve
        put :flip
        get :activities
      end
      resources :votes
    end
    resources :idea_revisions do
      member do
        get :clean
      end
    end
    resources :points
    resources :ads do
      collection do
        post :preview
      end
      member do
        post :skip
      end
    end
  end

  resources :activities do
    member do
      put :undelete
      get :unhide
    end
    resources :following_discussions, :as=>"followings"
    resources :comments do
      collection do
        get :more
      end
      member do
        get :unhide
        get :flag
        post :not_abusive
        post :abusive
      end
    end
  end

  resources :points do
    member do
      get :flag
      post :not_abusive
      post :abusive
      get :activity
      get :discussions
      post :quality
      post :unquality
      get :unhide
    end
    collection do
      get :newest
      get :revised
      get :your_ideas
      get :your_index
    end
    resources :revisions do
      member do
        get :clean
      end
    end
  end

  resources :color_schemes do
    collection do
      put :preview
    end
  end

  resources :instances do
    member do
      get :apis
    end
  end

  resources :widgets do
    collection do
      get :ideas
      get :discussions
      get :points
      get :preview_iframe
      post :preview
    end
  end

  resources :bulletins do
    member do
      post :add_inline
    end
  end

  resources :searches do
    collection do
      get :all
    end
  end

  resources :signups
  resources :endorsements
  resources :unsubscribes
  resources :notifications
  resources :about
  resources :tags
  resources :delayed_jobs do
    member do
      get :top
      get :clear
    end
  end

  resource :open_id

  if ENV['YRPRI_SET_HOME_TO_WORLD']
    match '/' => 'home#world'
  else
    match '/' => 'home#index'
  end
  match '/unsubscribe' => 'unsubscribes#new', :as => :unsubscribe
  match '/yours' => 'ideas#yours'
  match '/hot' => 'ideas#hot'
  match '/cold' => 'ideas#cold'
  match '/new' => 'ideas#new'
  match '/controversial' => 'ideas#controversial'
  match '/vote/:action/:code' => 'vote#index'
  match '/welcome' => 'home#index'
  match '/search' => 'searches#index'
  match '/splash' => 'splash#index'
  match '/issues' => 'issues#index'
  match '/issues.:format' => 'issues#index'
  match '/issues/:id' => 'issues#show', as: 'issue'
  match '/issues/:id.:format' => 'issues#show'
  match '/issues/:id/:action' => 'issues#index'
  match '/issues/:id/:action.:format' => 'issues#index'
  match '/pictures/:short_name/:action/:id' => 'pictures#index'
  match ':controller' => '#index'
  match ':controller/:action' => '#index'
  match ':controller/:action.:format' => '#index'
  match '/:controller(/:action(/:id))'
  match ':redirect' => redirect("/404.html"), :as => :catchall , :constraints => { :redirect => /.*/i }
end
  # The idea is based upon order of creation:
  # first created -> highest idea.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  before_filter :authenticate_user!
  
  def authorized?
    @notification = Notification.find(params[:id])
    current_user.is_admin? or @notification.recipient_id == current_user.id
  end

  # GET /notifications/1
  # GET /notifications/1.xml
  def show
    respond_to do |format|
      format.html
      format.xml { render :xml => @notification.to_xml(:include => [:sender, :notifiable], :except => NB_CONFIG['api_exclude_fields']) }
      format.json { render :json => @notification.to_json(:include => [:sender, :notifiable], :except => NB_CONFIG['api_exclude_fields']) }
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.xml
  def destroy
    @notification.remove!
    respond_to do |format|
      format.html { redirect_to(:controller => "inbox", :action => "notifications") }
      format.js {
        render :update do |page|
          page.remove 'notification_' + @notification.id.to_s
        end        
      }
    end
  end
end

app/views/notifications/_notificationchangeproposed.html.haml
%img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/fugue/envelope.png"}", :width => "16"}/
= tr("{sender_name} proposed {new_idea_name} acquire {idea_name}. <a href='{change_url}'>Please review</a>.", "view/notifications/_notificationchangeproposed", :sender_name => link_to(notification.sender_name,notification.sender), :new_idea_name => link_to(notification.notifiable.new_idea.name, notification.notifiable.new_idea), :idea_name => link_to(notification.notifiable.idea ? notification.notifiable.idea.name : "deleted", notification.notifiable.idea), :change_url => idea_change_url(notification.notifiable.idea,notification.notifiable)) if notification.notifiable.idea

app/views/notifications/_notificationchangeproposed_link.html.haml
= url_for idea_change_url(notification.notifiable.change.idea,notification.notifiable.change)

app/views/notifications/_notificationchangevote_link.html.haml
= url_for idea_change_url(notification.notifiable.change.idea,notification.notifiable.change)

app/views/notifications/_notificationcomment.html.haml
%img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/assets/icons/comment.png"}", :width => "16"}/
- if notification.notifiable
  - if notification.notifiable.activity.has_point?
    = tr("{sender_name} commented on {comment_name}", "view/notifications/_notificationcomment", :sender_name => link_to(notification.sender_name, notification.sender), :comment_name => link_to(notification.notifiable.activity.point.name, activity_comments_url(notification.notifiable.activity) + '#' + notification.notifiable.id.to_s))
  - elsif notification.notifiable.activity.has_idea?
    = tr("{sender_name} commented on {comment_name}", "view/notifications/_notificationcomment", :sender_name => link_to(notification.sender_name, notification.sender), :comment_name => link_to(notification.notifiable.activity.idea.name, activity_comments_url(notification.notifiable.activity) + '#' + notification.notifiable.id.to_s))
  - elsif notification.notifiable.activity.class == ActivityBulletinProfileNew
    = tr("{sender_name} left a comment on {user_name} profile", "view/notifications/_notificationcomment", :sender_name => link_to(notification.sender_name, notification.sender), :comment_url => activity_comments_url(notification.notifiable.activity) + '#' + notification.notifiable.id.to_s, :user_name => notification.notifiable.activity.user.name)
  - else
    - if notification.notifiable.activity.user_id == notification.recipient_id
      = tr("{sender_name} commented on <a href='{comment_url}'>your activity</a>", "view/notifications/_notificationcomment", :sender_name => link_to(notification.sender_name, notification.sender), :comment_url => activity_comments_url(notification.notifiable.activity) + '#' + notification.notifiable.id.to_s)
    - else
      = tr("{sender_name} commented on <a href='{comment_url}'>{user_name} activity</a>", "view/notifications/_notificationcomment", :sender_name => link_to(notification.sender_name, notification.sender), :comment_url => activity_comments_url(notification.notifiable.activity) + '#' + notification.notifiable.id.to_s, :user_name => notification.notifiable.activity.user.name)
- else
  = tr("No notifiable for notification: #{notification.id}")

app/views/notifications/_notificationcomment_link.html.haml
= url_for activity_comments_url(notification.notifiable.activity) + '#' + notification.notifiable.id.to_s

app/views/notifications/_notificationcommentflagged.html.haml
%img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/assets/icons/error.png"}", :width => "16"}/
- if notification and notification.sender and notification.notifiable
  = tr("{sender_name} flagged a comment by {user_name}", "view/notifications/_notificationcommentflagged", :sender_name => link_to(notification.sender.login, notification.sender), :user_name => link_to(notification.notifiable.user.name, activity_comments_url(notification.notifiable.activity) + '#' + notification.notifiable.id.to_s))

app/views/notifications/_notificationcontactjoined_link.html.haml
= url_for notification.sender

app/views/notifications/_notificationfollower.html.haml
%img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/assets/icons/user_add.png"}", :width => "16"}/
= tr("{sender_name} is now following your updates", "view/notifications/_notificationfollower", :sender_name => link_to(notification.sender_name, notification.sender))

app/views/notifications/_notificationideafinished.html.haml
- if notification.notifiable.idea.is_successful?
  %img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/fugue/star.png"}", :width => "16"}/
  = tr("{idea_name} was completed successfully", "view/notifications/_notificationideafinished", :idea_name => link_to(notification.notifiable.idea.name, notification.notifiable.idea))
- elsif notification.notifiable.idea.is_compromised?
  %img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/fugue/star_half.png"}", :width => "16"}/
  = tr("{idea_name} was completed with a compromise", "view/notifications/_notificationideafinished", :idea_name => link_to(notification.notifiable.idea.name, notification.notifiable.idea))
- elsif notification.notifiable.idea.is_failed?
  %img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/fugue/star_empty.png"}", :width => "16"}/
  = tr("{idea_name} failed", "view/notifications/_notificationideafinished", :idea_name => link_to(notification.notifiable.idea.name, notification.notifiable.idea))
- elsif notification.notifiable.idea.is_intheworks?
  %img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/fugue/hammer.png"}", :width => "16"}/
  = tr("{idea_name} is in the works", "view/notifications/_notificationideafinished", :idea_name => link_to(notification.notifiable.idea.name, notification.notifiable.idea))

app/views/notifications/_notificationideaflagged.html.haml
%img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/assets/icons/flag_yellow.png"}", :width => "16"}/
= tr("{sender_name} flagged {idea_name} for review", "view/notifications/_notificationideaflagged", :sender_name => link_to(notification.sender_name, notification.sender), :idea_name => link_to(notification.notifiable_name, notification.notifiable))

app/views/notifications/_notificationpointflagged.html.haml
%img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/assets/icons/flag_yellow.png"}", :width => "16"}/
= tr("{sender_name} flagged {point_name} for review", "view/notifications/_notificationpointflagged", :sender_name => link_to(notification.sender_name, notification.sender), :point_name => link_to(notification.notifiable_name, notification.notifiable))

app/views/notifications/_notificationpointflagged_link.html.haml
= url_for notification.notifiable

app/views/notifications/_notificationpointrevision.html.haml
%img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/assets/icons/comment_edit.png"}", :width => "16"}/
= tr("{sender_name} revised {point_name}", "view/notifications/_notificationpointrevision", :sender_name => link_to(notification.sender_name, notification.sender), :point_name => link_to(notification.notifiable.point.name, point_revision_url(notification.notifiable.point,notification.notifiable)))

app/views/notifications/_notificationwarning2.html.haml
%img.notification_icon{:border => "0", :height => "16", :src => "#{asset_path "/assets/icons/error_delete.png"}", :width => "16"}/
- if notification.notifiable.class == Comment
  = tr("This is your {warning_number} warning. You violated the <a href='/about/rules'>site rules</a> with <a href='{content_url}'>this {content_type} </a> - #{notification.custom_text}", "view/notifications/_notificationwarning", |
    :warning_number => tr('second','notifications'),                                                                                                                                                     |
    :content_url => activity_comments_url(notification.notifiable.activity_id) + "#" + notification.notifiable.id.to_s,                                                                                  |
    :content_type => tr("comment",'notifications'))                                                                                                                                                      |
- elsif notification.notifiable.class == Idea
  = tr("This is your {warning_number} warning. You violated the <a href='/about/rules'>site rules</a> with <a href='{content_url}'> {content_type} </a> - #{notification.custom_text}", "view/notifications/_notificationwarning", |
    :warning_number => tr('second','notifications'),                                                                                                                                                     |
    :content_url => idea_url(notification.notifiable.id),                                                                                                                                            |
    :content_type => tr("{idea_name}",'notifications', :idea_name=>Idea.unscoped.find(notification.notifiable.id).name))                                                                                                                                           |
- elsif notification.notifiable.class == Point
  = tr("This is your {warning_number} warning. You violated the <a href='/about/rules'>site rules</a> with <a href='{content_url}'>this {content_type} </a> - #{notification.custom_text}", "view/notifications/_notificationwarning", |
    :warning_number => tr('second','notifications'),                                                                                                                                                     |
    :content_url => point_url(notification.notifiable.id),                                                                                                                                               |
    :content_type => tr("Point",'notifications'))                                                                                                                                                        |