config/routes.rb
#require ‘sidekiq/web’

YourPriorities::Application.routes.draw do
  match '/donations/thank_you' => 'donations#thank_you'
  match '/donations/estartup' => 'donations#estartup'
  match '/donations/status' => 'donations#status'
  match '/donations/thank_you_estartup' => 'donations#thank_you_estartup'

 # mount Sidekiq::Web, at: ‘/sidekiq’

  resources :donations

  resources :subscriptions
  resources :plans
  resources :pages
  #mount Resque::Server.new, :at => '/resque' if Rails.env.production?

  mount Tolk::Engine => '/tolk', :as => 'tolk'

  devise_for :users, controllers: {
    sessions: "sessions",
    invitations:"users/invitations",
    registrations: "registrations",
    passwords: "passwords",
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  #mount Monologue::Engine, at: '/blog'

  resources :categories

  match '/groups/suggest_user' => 'groups#suggest_user'

  match '/users/eula' => 'users#eula'

  match "/about/rules" => redirect("/pages/2")
  match "/about/faq" => redirect("/pages/2")

  match '/ideas/flag/:id' => 'ideas#flag'
  match '/ideas/abusive/:id' => 'ideas#abusive'
  match '/ideas/not_abusive/:id' => 'ideas#not_abusive'
  match '/admin/all_flagged' => 'admin#all_flagged'
  match '/admin/statistics' => 'admin#statistics'
  match '/admin/all_deleted' => 'admin#all_deleted'
  match '/users/list_suspended' => 'users#list_suspended'
  match '/users/additional_information' => 'users#additional_information'
  match '/users/destroy_from_admin' => 'users#destroy_from_admin'

  match '/subscription_accounts/select_plan' => 'subscription_accounts#select_plan'
  match 'authenticate_from_island_is' =>'users#authenticate_from_island_is'
  match '/sub_instances/setup_status' =>'sub_instances#setup_status'

  resources :subscription_accounts do
    collection do
      get :users
      get :about
    end
  end

  resources :groups

  resources :sub_instances do
    member do
      get :email
      get :picture
      put :picture_save
    end
  end

  resources :users do
  	resource :profile
  	collection do
  	  get :endorsements
  	  post :order
  	end
  	member do
  	  put :suspend
      put :unsuspend
      get :activities
      get :comments
  	  get :points
  	  get :discussions
  	  get :capital
  	  put :impersonate
  	  get :followers
  	  get :documents
  	  get :stratml
  	  get :ignorers
  	  get :following
  	  get :ignoring
  	  post :follow
  	  post :unfollow
  	  get :make_admin
      get :unmake_admin
  	  get :ads
  	  get :ideas
  	  get :signups
  	  post :endorse
  	  get :resend_activation
    end
    resources :messages
    resources :followings do
      collection do
        put :multiple
      end
    end
    resources :user_contacts, :as => "contacts" do
      collection do
        put :multiple
        get :following
        get :members
        get :not_invited
        get :invited
      end
    end
  end

  resources :settings do
    collection do
      get :signups
      get :picture
      put :picture_save
      get :legislators
      post :legislators_save
      get :delete
    end
  end

  resources :ideas do
  	member do
      get :statistics
      put :flag_inappropriate
      get :flag
      put :bury
      put :compromised
      put :successful
      put :failed
      put :intheworks
      post :endorse
      get :endorsed
      get :opposed
      get :activities
      get :endorsers
      get :opposers
      get :discussions
      put :create_short_url
      post :tag
      put :tag_save
      get :points
      get :opposer_points
      get :endorser_points
      get :neutral_points
      get :everyone_points
      get :top_points
      get :idea_detail
      get :endorsed_points
      get :opposed_top_points
      get :endorsed_top_points
      get :comments
      get :documents
      get :update_status
      get :move
      post :move
      get :change_category
      put :change_category
  	end
  	collection do
      get :yours
      get :yours_finished
      get :yours_top
      get :yours_ads
      get :yours_lowest
      get :yours_created
      get :network
      get :consider
      get :finished
      get :finished_in_progress
      get :finished_successful
      get :finished_failed
      get :finished_compromised
      get :ads
      get :top
      get :by_tag
      get :by_impressions
      get :most_discussed
      get :all_tags
      get :top_24hr
      get :top_7days
      get :top_30days
      get :rising
      get :falling
      get :controversial
      get :random
      get :newest
      get :untagged
      get :revised
  	end
    resources :changes do
      member do
        put :start
        put :stop
        put :approve
        put :flip
        get :activities
      end
      resources :votes
    end
    resources :idea_revisions do
      member do
        get :clean
      end
    end
    resources :points
    resources :ads do
      collection do
        post :preview
      end
      member do
        post :skip
      end
    end
  end

  resources :activities do
    member do
      put :undelete
      get :unhide
    end
    resources :following_discussions, :as=>"followings"
    resources :comments do
      collection do
        get :more
      end
      member do
        get :unhide
        get :flag
        post :not_abusive
        post :abusive
      end
    end
  end

  resources :points do
    member do
      get :flag
      post :not_abusive
      post :abusive
      get :activity
      get :discussions
      post :quality
      post :unquality
      get :unhide
    end
    collection do
      get :newest
      get :revised
      get :your_ideas
      get :your_index
    end
    resources :revisions do
      member do
        get :clean
      end
    end
  end

  resources :color_schemes do
    collection do
      put :preview
    end
  end

  resources :instances do
    member do
      get :apis
    end
  end

  resources :widgets do
    collection do
      get :ideas
      get :discussions
      get :points
      get :preview_iframe
      post :preview
    end
  end

  resources :bulletins do
    member do
      post :add_inline
    end
  end

  resources :searches do
    collection do
      get :all
    end
  end

  resources :signups
  resources :endorsements
  resources :unsubscribes
  resources :notifications
  resources :about
  resources :tags
  resources :delayed_jobs do
    member do
      get :top
      get :clear
    end
  end

  resource :open_id

  if ENV['YRPRI_SET_HOME_TO_WORLD']
    match '/' => 'home#world'
  else
    match '/' => 'home#index'
  end
  match '/unsubscribe' => 'unsubscribes#new', :as => :unsubscribe
  match '/yours' => 'ideas#yours'
  match '/hot' => 'ideas#hot'
  match '/cold' => 'ideas#cold'
  match '/new' => 'ideas#new'
  match '/controversial' => 'ideas#controversial'
  match '/vote/:action/:code' => 'vote#index'
  match '/welcome' => 'home#index'
  match '/search' => 'searches#index'
  match '/splash' => 'splash#index'
  match '/issues' => 'issues#index'
  match '/issues.:format' => 'issues#index'
  match '/issues/:id' => 'issues#show', as: 'issue'
  match '/issues/:id.:format' => 'issues#show'
  match '/issues/:id/:action' => 'issues#index'
  match '/issues/:id/:action.:format' => 'issues#index'
  match '/pictures/:short_name/:action/:id' => 'pictures#index'
  match ':controller' => '#index'
  match ':controller/:action' => '#index'
  match ':controller/:action.:format' => '#index'
  match '/:controller(/:action(/:id))'
  match ':redirect' => redirect("/404.html"), :as => :catchall , :constraints => { :redirect => /.*/i }
end
  # The idea is based upon order of creation:
  # first created -> highest idea.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController

  before_filter :get_point
  before_filter :authenticate_user!, :except => [:show, :clean]
  before_filter :authenticate_admin!, :only => [:destroy, :update, :edit]

  # GET /points/1/revisions
  def index
    redirect_to @point
    return
  end

  # GET /points/1/revisions/1
  def show
    if @point.is_removed?
      flash[:error] = tr("That point was deleted", "controller/revisions")
      redirect_to @point.idea
      return
    end    
    @revision = @point.revisions.find(params[:id])
    @page_title = tr("{user_name} revision of {point_name}", "controller/revisions", :user_name => @revision.user.name.possessive, :point_name => @revision.name)
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /points/1/revisions/1/clean
  def clean
    @revision = @point.revisions.find(params[:id])
    @page_title = tr("{user_name} revision of {point_name}", "controller/revisions", :user_name => @revision.user.name.possessive, :point_name => @revision.name)
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /points/1/revisions/new
  def new
    @revision = @point.revisions.new
    @revision.name = @point.name
    @revision.content = @point.content
    @revision.website = @point.website
    @revision.value = @point.value
    @revision.other_idea = @point.other_idea
    @page_title = tr("Revise {point_name}", "controller/revisions", :point_name => @point.name)    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /points/1/revisions/1/edit
  def edit
    @revision = @point.revisions.find(params[:id])
  end

  # POST /points/1/revisions
  def create
    @revision = @point.revisions.new(params[:revision])
    @revision.user = current_user
    respond_to do |format|
      if @revision.save
        @revision.publish!
        # this is all to add a comment with their note
        if params[:comment] and params[:comment][:content] and params[:comment][:content].length > 0
          activities = Activity.find(:all, :conditions => ["user_id = ? and type like 'ActivityPointRevision%' and created_at > '#{Time.now-5.minutes}'",current_user.id], :order => "created_at desc")
          if activities.any?
            activity = activities[0]
            @comment = activity.comments.new(params[:comment])
            @comment.user = current_user
            @comment.request = request
            if activity.idea
              # if this is related to a idea, check to see if they endorse it
              e = activity.idea.endorsements.active_and_inactive.find_by_user_id(@comment.user.id)
              @comment.is_endorser = true if e and e.is_up?
              @comment.is_opposer = true if e and e.is_down?
            end
            @comment.save(:validate => false)            
          end
        end
        flash[:notice] = tr("Revised {point_name}", "controller/revisions", :point_name => @point.name)
        format.html { redirect_to(@point) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /points/1/revisions/1
  def update
    @revision = @point.revisions.find(params[:id])
    respond_to do |format|
      if @revision.update_attributes(params[:revision])
        flash[:notice] = tr("Revised {point_name}", "controller/revisions", :point_name => @point.name)
        format.html { redirect_to(@revision) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /points/1/revisions/1
  def destroy
    @revision = @point.revisions.find(params[:id])
    flash[:notice] = tr("Deleted revision of {point_name}", "controller/revisions", :point_name => @point.name)
    @revision.destroy

    respond_to do |format|
      format.html { redirect_to(revisions_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  def get_point
    @point = Point.unscoped.find(params[:point_id])
    @idea = @point.idea
  end
  
end

app/views/revisions/_revisions.html.haml
%p
  .heading
    = tr("Revisions", "view/revisions/_revisions")
  - for revision in @point.revisions.by_recently_created
    %table{:border => "0", :cellpadding => "0", :cellspacing => "0"}
      %tr
        %td{:valign => "top", :width => "24"}
          = render :partial => "users/pic", :locals => {:user => revision.user}
        %td{:style => "padding-left: 5px;", :valign => "top"}
          - if revision.user.status == 'suspended' or revision.user.status == 'removed'
            %strike/
          = link_to_unless_current tr("{user_name} revision", "view/revisions/_revisions", :user_name => revision.user.name), point_revision_url(@point,revision)
          - if revision.user.status == 'suspended' or revision.user.status == 'removed'
            .profile_small= time_ago(revision.created_at)
    %p

app/views/revisions/clean.html.haml
= render :partial => "points/header"
= render :partial => "points/nav"
%table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
  %tr
    %td{:valign => "top"}
      - if @point.revision_id != @revision.id
        %p
        .notice
          = tr("Here's what this point looked like {time_ago}. You can also <a href='{revision_url}'>see the changes</a> in this version from the previous one.", "view/revisions/clean", :revision_url => point_revision_url(@point,@revision), :time_ago => time_ago(@revision.created_at))
      %p
      .point_content_detail
        = @revision.content_html
      - if @revision.has_website?
        .point_source
          = tr("Source:", "view/revisions/clean")
          %a{:href => @revision.website_link}= truncate(@revision.website_link,:length=>70)
    %td{:style => "padding-left: 20px;", :valign => "top", :width => "150"}
      = render :partial => "revisions"

app/views/revisions/edit.html.haml
= form_for(@revision) do |f|
  = f.error_messages
  %p
    = f.label :point_id
    %br/
    = f.text_field :point_id
  %p
    = f.label :idea_id
    %br/
    = f.text_field :idea_id
  %p
    = f.label :other_idea_id
    %br/
    = f.text_field :other_idea_id
  %p
    = f.label :user_id
    %br/
    = f.text_field :user_id
  %p
    = f.label :value
    %br/
    = f.text_field :value
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :content
    %br/
    = f.text_area :content
  %p
    = f.submit "Update"

app/views/revisions/new.html.haml
= render :partial => "points/header"
.col-group
  .col-1
    .col-content
      &nbsp;
  .col-8
    .col-content
      = render :partial => "points/nav"
      %p= tr("<p>You can help the debate by adding your point.</p>", "view/revisions/new")
      = form_for :revision, :url => point_revisions_path(@point)  do |f|
        = f.error_messages :header_message => tr("Please review", "view/revisions/new"), :message => tr("We need a change to your point", "view/revisions/new")
        %p= tr("Summarize your point in <span class='small'>60 characters</span>", "view/revisions/new")
        = f.text_field :name, :size => 50, :maxlength => 60
        %p= tr("Is this point {support_radio} in support or {oppose_radio} in opposition to {idea_name}?", "view/revisions/new", :idea_name => link_to(@idea.name, @idea), :support_radio => f.radio_button(:value, 1), :oppose_radio => f.radio_button(:value, -1), :neutral_radio => f.radio_button(:value, 0))
        = tr("Explain your point.", "view/revisions/new")
        %p= tr("characters left", "view/revisions/new")
        = f.text_area :content, :id => 'revisionContent', :button => 'submit', :rows => 5, :cols => 60, :maxLength => 500
        %p= tr("Include a website source link", "view/revisions/new")
        = f.text_field :website, :size => 50
        %p= tr("Link this to another idea <span class='small'>Just start typing the name</span>", "view/revisions/new")
        = f.text_field :other_idea_name, :size => 50, :autocomplete => "off"
        %p= tr("Linking to another idea is optional. If your point is in opposition - you can link to a better idea. ir if your point is supportive you can highlight a more specific or related idea.", "view/revisions/new")
        %p= tr("Why did you make this change?", "view/revisions/new")
        = fields_for :comment do |c|
          = c.text_field :content, :size => 50
        %br
        = f.submit tr("Save point", "view/revisions/new"), :id => "submit", :class => "yellow_button"
      = link_to tr("Cancel this revision", "view/revisions/new"), @point
  .col-3
    .col-content
      = render :partial => "points/authors", :locals => {:users => @point.authors }

app/views/revisions/show.html.haml
= render :partial => "points/header"
.col-group
  .col-1
    .col-content
      &nbsp;
  .col-8
    .col-content
      = render :partial => "points/nav"
      - if @revision.attribute_present?("content_diff")
        %p
        .notice
          = tr("This shows the changes from the previous revision. You can also <a href='{clean_url}'>see the clean version</a>", "view/revisions/show", :clean_url => clean_point_revision_url(@point,@revision))
        %p
        .point_content_detail
          = @revision.content_diff.html_safe
        - if @revision.has_website?
          .point_source
            = tr("Source:", "view/revisions/show")
            %a{:href => @revision.website_link}= truncate(@revision.website_link,:length=>70)
      - else
        %p
        .notice
          = tr("Normally, you would see the changes made here, but there was some kind of processing error, so please check out the <a href='{clean_url}'>clean version</a>", "view/revisions/show", :clean_url => clean_point_revision_url(@point,@revision))
      %p
      .heading= tr("Recent activity on this point", "view/revisions/show")
      - for activity in @revision.activities.active
        = render :partial => "activities/show", :locals => {:activity => activity, :suffix => "_noself" }
  .col-3
    .col-content
      = render :partial => "revisions"