config/routes.rb
#require ‘sidekiq/web’

YourPriorities::Application.routes.draw do
  match '/donations/thank_you' => 'donations#thank_you'
  match '/donations/estartup' => 'donations#estartup'
  match '/donations/status' => 'donations#status'
  match '/donations/thank_you_estartup' => 'donations#thank_you_estartup'

 # mount Sidekiq::Web, at: ‘/sidekiq’

  resources :donations

  resources :subscriptions
  resources :plans
  resources :pages
  #mount Resque::Server.new, :at => '/resque' if Rails.env.production?

  mount Tolk::Engine => '/tolk', :as => 'tolk'

  devise_for :users, controllers: {
    sessions: "sessions",
    invitations:"users/invitations",
    registrations: "registrations",
    passwords: "passwords",
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  #mount Monologue::Engine, at: '/blog'

  resources :categories

  match '/groups/suggest_user' => 'groups#suggest_user'

  match '/users/eula' => 'users#eula'

  match "/about/rules" => redirect("/pages/2")
  match "/about/faq" => redirect("/pages/2")

  match '/ideas/flag/:id' => 'ideas#flag'
  match '/ideas/abusive/:id' => 'ideas#abusive'
  match '/ideas/not_abusive/:id' => 'ideas#not_abusive'
  match '/admin/all_flagged' => 'admin#all_flagged'
  match '/admin/statistics' => 'admin#statistics'
  match '/admin/all_deleted' => 'admin#all_deleted'
  match '/users/list_suspended' => 'users#list_suspended'
  match '/users/additional_information' => 'users#additional_information'
  match '/users/destroy_from_admin' => 'users#destroy_from_admin'

  match '/subscription_accounts/select_plan' => 'subscription_accounts#select_plan'
  match 'authenticate_from_island_is' =>'users#authenticate_from_island_is'
  match '/sub_instances/setup_status' =>'sub_instances#setup_status'

  resources :subscription_accounts do
    collection do
      get :users
      get :about
    end
  end

  resources :groups

  resources :sub_instances do
    member do
      get :email
      get :picture
      put :picture_save
    end
  end

  resources :users do
  	resource :profile
  	collection do
  	  get :endorsements
  	  post :order
  	end
  	member do
  	  put :suspend
      put :unsuspend
      get :activities
      get :comments
  	  get :points
  	  get :discussions
  	  get :capital
  	  put :impersonate
  	  get :followers
  	  get :documents
  	  get :stratml
  	  get :ignorers
  	  get :following
  	  get :ignoring
  	  post :follow
  	  post :unfollow
  	  get :make_admin
      get :unmake_admin
  	  get :ads
  	  get :ideas
  	  get :signups
  	  post :endorse
  	  get :resend_activation
    end
    resources :messages
    resources :followings do
      collection do
        put :multiple
      end
    end
    resources :user_contacts, :as => "contacts" do
      collection do
        put :multiple
        get :following
        get :members
        get :not_invited
        get :invited
      end
    end
  end

  resources :settings do
    collection do
      get :signups
      get :picture
      put :picture_save
      get :legislators
      post :legislators_save
      get :delete
    end
  end

  resources :ideas do
  	member do
      get :statistics
      put :flag_inappropriate
      get :flag
      put :bury
      put :compromised
      put :successful
      put :failed
      put :intheworks
      post :endorse
      get :endorsed
      get :opposed
      get :activities
      get :endorsers
      get :opposers
      get :discussions
      put :create_short_url
      post :tag
      put :tag_save
      get :points
      get :opposer_points
      get :endorser_points
      get :neutral_points
      get :everyone_points
      get :top_points
      get :idea_detail
      get :endorsed_points
      get :opposed_top_points
      get :endorsed_top_points
      get :comments
      get :documents
      get :update_status
      get :move
      post :move
      get :change_category
      put :change_category
  	end
  	collection do
      get :yours
      get :yours_finished
      get :yours_top
      get :yours_ads
      get :yours_lowest
      get :yours_created
      get :network
      get :consider
      get :finished
      get :finished_in_progress
      get :finished_successful
      get :finished_failed
      get :finished_compromised
      get :ads
      get :top
      get :by_tag
      get :by_impressions
      get :most_discussed
      get :all_tags
      get :top_24hr
      get :top_7days
      get :top_30days
      get :rising
      get :falling
      get :controversial
      get :random
      get :newest
      get :untagged
      get :revised
  	end
    resources :changes do
      member do
        put :start
        put :stop
        put :approve
        put :flip
        get :activities
      end
      resources :votes
    end
    resources :idea_revisions do
      member do
        get :clean
      end
    end
    resources :points
    resources :ads do
      collection do
        post :preview
      end
      member do
        post :skip
      end
    end
  end

  resources :activities do
    member do
      put :undelete
      get :unhide
    end
    resources :following_discussions, :as=>"followings"
    resources :comments do
      collection do
        get :more
      end
      member do
        get :unhide
        get :flag
        post :not_abusive
        post :abusive
      end
    end
  end

  resources :points do
    member do
      get :flag
      post :not_abusive
      post :abusive
      get :activity
      get :discussions
      post :quality
      post :unquality
      get :unhide
    end
    collection do
      get :newest
      get :revised
      get :your_ideas
      get :your_index
    end
    resources :revisions do
      member do
        get :clean
      end
    end
  end

  resources :color_schemes do
    collection do
      put :preview
    end
  end

  resources :instances do
    member do
      get :apis
    end
  end

  resources :widgets do
    collection do
      get :ideas
      get :discussions
      get :points
      get :preview_iframe
      post :preview
    end
  end

  resources :bulletins do
    member do
      post :add_inline
    end
  end

  resources :searches do
    collection do
      get :all
    end
  end

  resources :signups
  resources :endorsements
  resources :unsubscribes
  resources :notifications
  resources :about
  resources :tags
  resources :delayed_jobs do
    member do
      get :top
      get :clear
    end
  end

  resource :open_id

  if ENV['YRPRI_SET_HOME_TO_WORLD']
    match '/' => 'home#world'
  else
    match '/' => 'home#index'
  end
  match '/unsubscribe' => 'unsubscribes#new', :as => :unsubscribe
  match '/yours' => 'ideas#yours'
  match '/hot' => 'ideas#hot'
  match '/cold' => 'ideas#cold'
  match '/new' => 'ideas#new'
  match '/controversial' => 'ideas#controversial'
  match '/vote/:action/:code' => 'vote#index'
  match '/welcome' => 'home#index'
  match '/search' => 'searches#index'
  match '/splash' => 'splash#index'
  match '/issues' => 'issues#index'
  match '/issues.:format' => 'issues#index'
  match '/issues/:id' => 'issues#show', as: 'issue'
  match '/issues/:id.:format' => 'issues#show'
  match '/issues/:id/:action' => 'issues#index'
  match '/issues/:id/:action.:format' => 'issues#index'
  match '/pictures/:short_name/:action/:id' => 'pictures#index'
  match ':controller' => '#index'
  match ':controller/:action' => '#index'
  match ':controller/:action.:format' => '#index'
  match '/:controller(/:action(/:id))'
  match ':redirect' => redirect("/404.html"), :as => :catchall , :constraints => { :redirect => /.*/i }
end
  # The idea is based upon order of creation:
  # first created -> highest idea.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

app/controllers/home_controller.rb
class HomeController < ApplicationController

  caches_action :index,
                :if => proc {|c| c.do_action_cache? },
                :cache_path => proc {|c| c.action_cache_path},
                :expires_in => 30.seconds

  caches_action :categories,
                :if => proc {|c| c.do_action_cache? },
                :cache_path => proc {|c| c.action_cache_path},
                :expires_in => 30.seconds

  caches_action :world,
                :if => proc {|c| c.do_action_cache? },
                :cache_path => proc {|c| c.action_cache_path},
                :expires_in => 30.seconds

  caches_action :about,
                :if => proc {|c| c.do_action_cache? },
                :cache_path => proc {|c| c.action_cache_path},
                :expires_in => 30.seconds

  caches_action :map,
                :cache_path => proc {|c| c.action_cache_path},
                :expires_in => 15.seconds

  def get_layout
    if ["world"].include?(action_name)
      return SubInstance.where(:short_name=>"default").first.home_page_layout
    elsif ["live"].include?(action_name)
      return "application"
    elsif ["about"].include?(action_name)
      return Instance.current.layout_for_subscriptions
    else
      return SubInstance.current.home_page_layout
    end
  end

  def blog
    #@post = Monologue::Post.find(params[:id])
    #@post = @post.posts_revisions.last
  end

  def about
    if Instance.current.about_page_name
      render :file=>Instance.current.about_page_name
    else
      redirect_to :back
    end
  end

  def categories
    @categories = Category.all
    @page_title = SubInstance.current.name
    @endorsements = nil
    @ideas = []
    @ideas << @categories.first.ideas.first if @categories and @categories.first and @categories.first.ideas and @categories.first.ideas.first
    if user_signed_in? # pull all their endorsements on the ideas shown
      all_ideas = []
      @categories.each do |category|
       category.ideas.top_three.each do |idea|
         all_ideas << idea
       end
      end
      @endorsements = current_user.endorsements.active.find(:all, :conditions => ["idea_id in (?)", all_ideas.collect {|c| c.id}])
    end
    last = params[:last].blank? ? Time.now + 1.second : Time.parse(params[:last])
    @activities = Activity.active.top.for_all_users.paginate(:page => params[:page])
  end

  def live
    @activities = Activity.active.top.for_all_users.paginate(:page => params[:page])
  end

  def index
    @position_in_idea_name = false
    @skip_sub_navigation = true
    if current_instance.domain_name.include?("yrpri") and (not request.subdomains.any? or request.subdomains[0] == 'www' and not params[:sub_instance_short_name]) and not SubInstance.current.lock_users_to_instance==true
      redirect_to :action=>"world"
    elsif SubInstance.current.use_live_home_page and SubInstance.current.use_live_home_page==true
      redirect_to :action=>"live"
    elsif SubInstance.current.use_category_home_page and SubInstance.current.use_category_home_page==true
      redirect_to :action=>"categories"
    else
      @page_title = SubInstance.current.name
      @ideas = @new_ideas = Idea.published.newest.limit(3)
      @top_ideas = Idea.published.top_7days.limit(3).reject{|idea| @new_ideas.include?(idea)} unless @block_endorsements
      @random_ideas = Idea.published.by_random.limit(3).reject{|idea| @new_ideas.include?(idea) or (@top_ideas and @top_ideas.include?(idea))}
      if params[:successful]
        @finished_ideas = Idea.successful.not_removed.by_random.top_rank.limit(3)
      elsif params[:failed]
        @finished_ideas = Idea.failed.not_removed.by_random.top_rank.limit(3)
      elsif params[:in_progress]
        @finished_ideas = Idea.in_progress.not_removed.by_random.top_rank.limit(3)
      else
        @finished_ideas = Idea.successful.not_removed.by_random.top_rank.limit(3)
      end

      all_ideas = []
      all_ideas += @new_ideas if @new_ideas
      all_ideas += @top_ideas if @top_ideas
      all_ideas += @random_ideas if @random_ideas
      all_ideas += @finished_ideas if @finished_ideas

      @endorsements = nil
      if user_signed_in? # pull all their endorsements on the ideas shown
        @endorsements = current_user.endorsements.active.find(:all, :conditions => ["idea_id in (?)", all_ideas.collect {|c| c.id}])
      end

      last = params[:last].blank? ? Time.now + 1.second : Time.parse(params[:last])
      @activities = Activity.active.top.for_all_users.paginate(:page => params[:page])
      #@blog_posts = Monologue::Post.published.limit(3)
    end
  end

  def world
    if request.subdomains.any? and request.subdomains[0] != 'www'
      redirect_to "http://www.yrpri.org/home/world"
    else
      @position_in_idea_name = false
      @page_title = tr("{instance_name} Worldwide","shared/language_selection_master",:instance_name => current_instance.name)
      @ideas = @world_ideas = Idea.unscoped.where(:sub_instance_id=>SubInstance.find_by_short_name("united-nations").id).published.top_rank.limit(3)
      @eu_eea_ideas = Idea.unscoped.where(:sub_instance_id=>SubInstance.find_by_short_name("eu").id).published.top_rank.limit(3)
      @country_sub_instance = SubInstance.where(:iso_country_id=>@iso_country.id).first if @iso_country
      if @country_sub_instance
        @country_sub_instance_ideas = Idea.unscoped.where(:sub_instance_id=>@country_sub_instance.id).published.top_rank.limit(3)
      else
        @country_sub_instance_ideas = []
      end

      if @country_sub_instance
        @random_sub_instance = SubInstance.top10.reject {|x| x.id == @country_sub_instance.id or x.short_name.include?("test") or x.short_name.include?("Development") or x.short_name=="eu" or x.short_name=="united-nations"}.sample
      else
        @random_sub_instance = SubInstance.top10.reject {|x| x.short_name.include?("test") or x.short_name.include?("Development") or x.short_name=="eu" or x.short_name=="united-nations"}.sample
      end
      @random_sub_instance_ideas = Idea.unscoped.where(:sub_instance_id=>@random_sub_instance.id).published.top_rank.limit(3)

      all_ideas = []
      all_ideas += @country_sub_instance_ideas if @country_sub_instance_ideas
      all_ideas += @world_ideas if @world_ideas
      all_ideas += @eu_eea_ideas if @eu_eea_ideas
      all_ideas += @random_sub_instance_ideas if @random_sub_instance_ideas

      @endorsements = nil
      if user_signed_in? # pull all their endorsements on the ideas shown
        @endorsements = current_user.endorsements.active.find(:all, :conditions => ["idea_id in (?)", all_ideas.collect {|c| c.id}])
      end
    end
  end

  def map
    render :layout=>false, :content_type => 'application/xml'
  end

  def sub_instance_map
    @sub_instances = SubInstance.where("map_coordinates IS NOT NULL").all
    render :layout=>false, :content_type => 'application/xml'
  end

  def goto
    if params[:country_name] and params[:country_name]!=""
      country = IsoCountry.find_by_country_english_name(params[:country_name])
      sub_instance = SubInstance.find_by_iso_country_id(country.id)
      redirect_to sub_instance.show_url
    else
      redirect_to "/"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def all_countries_in_columns
    one = []
    two = []
    three = []
    four = []
    five = []
    six = []
    flip = 1

    IsoCountry.by_name.all.each do |a|
      if flip==1
        one << a
        flip = 2
      elsif flip==2
        two << a
        flip = 3
      elsif flip==3
        three << a
        flip = 4
      elsif flip==4
        four << a
        flip = 5
      elsif flip==5
        five << a
        flip = 6
      elsif flip==6
        six << a
        flip = 1
      end
    end
    [one,two,three,four,five,six]
  end

  EU_AND_EEA_COUNTRIES = ["at", "be", "bg", "cy", "cz", "dk", "ee", "fi", "fr", "de", "gr", "hu", "ie", "it", "lv", "lt", "lu", "mt", "nl", "pl", "pt", "ro", "sk", "si", "es", "se", "gb","is","no","li","ch"]

  def country_in_eu_or_eea?(country_code)
    EU_AND_EEA_COUNTRIES.include?(country_code.downcase)
  end

  def get_placemark_map_style(country)
    current_sub_instance = SubInstance.current
    SubInstance.current = SubInstance.find_by_iso_country_id(country.id)
    if sub_instance = SubInstance.find_by_iso_country_id(country.id) and Idea.where("sub_instance_id = ?", sub_instance.id).count>0
      ret = "#HasIdeasStyle"
    else
      ret = "#NoIdeaStyle"
    end
    SubInstance.current = SubInstance.current
    ret
  end
end

app/views/home/_country_options.html.haml
- cache(["country_options",locale,SubInstance.current_id,@inline_translations_enabled], :expires_in => 5.seconds) do
  .all_countries
    %table
      %tr
        - all_countries_in_columns.each do |column|
          %td{:align => "center"}
            - column.each do |country|
              - if sub_instance = SubInstance.find_by_iso_country_id(country.id)
                .country
                  = link_to sub_instance.show_url do
                    = image_tag country.large_flag_image, :size=>"32x32", :border=>0
                    %br
                      = country.country_english_name

app/views/home/_index.html.haml
:javascript
  $(function(){
  	$('.move_test').replaceWith($('.category'));
  	$('.replace_fblike').replaceWith($('.fblike'));
  	$('.replace_report').replaceWith($('.report1'));
  	$('.replace_notice').replaceWith($('.single .warning_inline2'));
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  });
- if false and @blog_posts.any?
  %div.home_welcome
    %h1.home_h1
      = tr("News", "view/ideas")
      = #link_to tr("News", "view/ideas"),"/blog"
    %table
      %tr
        - @blog_posts.each do |post|
          %td{:width=>"33%", :valign=>"top"}
            - post_revision = post.posts_revisions.last
            = render :partial=>"/home/blog_post", :locals=>{:post=>post_revision}
    %br
- if @finished_ideas.any?
  %div.home_welcome
    %h2.home_h1
      = link_to tr("In official status", "view/ideas", :count=>Idea.finished.not_removed.count), "/ideas/finished"
    %ul
      %li.successful{:style=>"display: inline;padding-right:10px;"}
        %b
          = link_to tr("Officially successful ({count})", "view/ideas", :count=>Idea.successful.not_removed.count), "/ideas/finished_successful"
      %li.failed{:style=>"display: inline;padding-right:10px;"}
        = link_to tr("Officially failed ({count})", "view/ideas",:count=>Idea.failed.not_removed.count), "/ideas/finished_failed"
      %li.in_progress{:style=>"display: inline;padding-right:10px;"}
        = link_to tr("Officially in progress ({count})", "view/ideas", :count=>Idea.in_progress.not_removed.count), "/ideas/finished_in_progress"
    - @finished_ideas.each do |idea|
      = render :partial=>"ideas/top_level_listing", :locals=>{:idea=>idea, :endorsements=>@endorsements}
      %div
        %div{:id => "idea_detail_#{idea.id}"}
    = "&nbsp;".html_safe
- if @random_ideas.any?
  %div.home_welcome
    %h2.home_h1
      = link_to tr("Random #{IDEA_TOKEN_PLURAL_CAPS}","home"),"/ideas/random"
    - @random_ideas.each do |idea|
      = render :partial=>"ideas/top_level_listing", :locals=>{:idea=>idea, :endorsements=>@endorsements}
      %div
        %div{:id => "idea_detail_#{idea.id}"}
- if @new_ideas.any?
  %div.home_welcome{:style=>"margin-top: 22px; padding-top: 22px;"}
    %h2.home_h1
      = link_to tr("New #{IDEA_TOKEN_PLURAL_CAPS}","home"), "ideas/newest"
    - @new_ideas.each do |idea|
      = render :partial=>"ideas/top_level_listing", :locals=>{:idea=>idea, :endorsements=>@endorsements}
      %div
        %div{:id => "idea_detail_#{idea.id}"}
- else
  .home_welcome
    %h2
      %br
      = tr("Welcome to your {instance_name}. Please add your first #{IDEA_TOKEN} ", "controller/sub_instances", :instance_name => current_instance.name)
      = link_to tr("here.","here"),"/ideas/new"
- if @top_ideas and @top_ideas.any?
  %div.home_welcome{:style=>"margin-top: 0px; padding-top: 0px;"}
    %h2.home_h2
      &nbsp;
    %h2.home_h1
      = link_to tr("Trending #{IDEA_TOKEN_PLURAL}", "controller/ideas"),"/ideas/top_7days"
    - @top_ideas.each do |idea|
      = render :partial=>"ideas/top_level_listing", :locals=>{:idea=>idea, :endorsements=>@endorsements}
      %div
        %div{:id => "idea_detail_#{idea.id}"}
- unless @activities.blank?
  %div.home_welcome
    %h2.home_h2
      &nbsp;
    %h2.home_h1
      = tr("Latest Activity","home")
    .endless_scroll_activities
      = render :partial => 'feed/activity_list_simple'
    = link_to tr("More...","here"), "/feed/top_feed?page?#{@activities.next_page}", :class => 'load-more-posts', :remote => true if @activities.next_page

app/views/home/_map_element.html.haml
- if place.map_coordinates
  - coordinate_array = JSON.parse(place.map_coordinates)
  :plain
    <Placemark>
          <name>#{place.name}</name>
          <styleUrl>#{get_placemark_map_style(place)}</styleUrl>
          <description>
          </description>
  - if coordinate_array.length>1
    :plain
      <MultiGeometry>
  - coordinate_array.each do |coordinates|
    = render :partial=>"map_polygon", :locals=>{:coordinates=>coordinates}
  - if coordinate_array.length>1
    :plain
      </MultiGeometry>
  :plain
      </Placemark>

app/views/home/_map_polygon.html.haml
:plain
  <Polygon>
            <outerBoundaryIs>
              <LinearRing>
                <coordinates>
                #{coordinates}
                </coordinates>
              </LinearRing>
            </outerBoundaryIs>
          </Polygon>

app/views/home/_simple_panel.html.haml
.panel.radius.panel-bg-2
  - sub_instance=SubInstance.find_by_short_name(short_name)
  .row
    .flag{:style=>"float:left;padding-right:30px;"}
      - begin
        = link_to sub_instance.show_url, :title=>title, :alt=>title do
          = image_tag flag_path, :border=>0
      - rescue
        - Rails.logger.error("Could not find sub instance logo file")
    .ideas{:style=>"float:left;"}
      - if ideas.any?
        - ideas.each do |idea|
          = render :partial=>"ideas/simple", :locals=>{:idea=>idea, :endorsements=>@endorsements}
      - else
        = tr("No idea has been created - be the first by clicking here: ","welcome")
        = link_to sub_instance.show_url, sub_instance.show_url

app/views/home/blog.html.haml
%blog
  %h1{:style=>"margin-left:-15px;"}
    = @post.title.strip
  %div
    = raw @post.content

app/views/home/categories.html.haml
- if false and SubInstance.current.message_to_users and SubInstance.current.message_to_users!=""
  = render :partial=>"/shared/top_message_box", :locals=> {:message_text => SubInstance.current.message_to_users.html_safe }
- for category in @categories
  .idea_listing
    %span
      %h2
        %a{:href => "#{category.to_url}"}
          = category.name
          = " (#{category.ideas.published.count})"
        - if not @block_new_ideas
          = " -"
          %span.small_text{:style=>""}
            = raw "<a href='/ideas/new?category_id=#{category.id}'>"+tr("Add new idea","model/category")+"</a>"
      - category.ideas.published.by_random.limit(3).each do |idea|
        = render :partial=>"ideas/top_level_listing", :locals=>{:idea=>idea, :endorsements=>@endorsements}
        %br
- unless @activities.blank?
  .row
    .large-12.columns
      %h2.home_h1
        = tr("Latest Activity","home")
      .endless_scroll_activities
        = render :partial => 'feed/activity_list_simple'
      = link_to tr("More...","here"), "/feed/top_feed?page?#{@activities.next_page}", :class => 'load-more-posts', :remote => true if @activities.next_page

app/views/home/index.html.haml
= render :partial=>SubInstance.current.home_page_partial

app/views/home/index.js.haml
$('.endless_scroll_activities').append('#{escape_javascript(render partial: "feed/activity_list_simple", :locals => { :activities => @activities })}');
$('a.load-more-posts').attr('href', '#{ "/feed/top_feed?page?#{@activities.next_page}"}');
 
- unless @activities.next_page
  $('a.load-more-posts').remove();

app/views/home/live.html.haml
.row
  .large-12.columns.panel-bg-2
    - if SubInstance.current.live_stream_id and SubInstance.current.live_stream_id!=""
      %h2
        = tr("Live stream","here")
      = raw "<iframe width='100%' height='315' src='//www.youtube.com/embed/#{SubInstance.current.live_stream_id}' frameborder='0' allowfullscreen></iframe>"
    - else
      %h2
        = tr("Welcome","here")
      = raw "<iframe width='100%' height='315' src='//www.youtube.com/embed/t0lFd1poJfs' frameborder='0' allowfullscreen></iframe>"
.row
  .large-12.columns
    - if current_user
      %h2
        = tr("Chat","here")
      = raw "<iframe src='https://irc.yrpri.org:7778/?nick=#{current_user.login.gsub(" ","_")}_?#{"#"+SubInstance.current.name.downcase.gsub(" ","_")}' style='border:0; width:100%; height:450px;'></iframe>"
    - else
      %h2
        = tr("Login to enable chat.","here")

- unless @activities.blank?
  .row
    .large-12.columns
      %h2.home_h1
        = tr("Latest Activity","home")
      .endless_scroll_activities
        = render :partial => 'feed/activity_list_simple'
      = link_to tr("More...","here"), "/feed/top_feed?page?#{@activities.next_page}", :class => 'load-more-posts', :remote => true if @activities.next_page

app/views/home/map.html.haml
= render :partial=>"map_header"
- IsoCountry.all.each do |country|
  = render :partial=>"map_element", :locals=>{:place=>country}
= render :partial=>"map_footer"

app/views/home/sub_instance_map.html.haml
= render :partial=>"map_header"
- @sub_instances.each do |sub_instance|
  = render :partial=>"map_element", :locals=>{:place=>sub_instance}
= render :partial=>"map_footer"