config/routes.rb
#require ‘sidekiq/web’

YourPriorities::Application.routes.draw do
  match '/donations/thank_you' => 'donations#thank_you'
  match '/donations/estartup' => 'donations#estartup'
  match '/donations/status' => 'donations#status'
  match '/donations/thank_you_estartup' => 'donations#thank_you_estartup'

 # mount Sidekiq::Web, at: ‘/sidekiq’

  resources :donations

  resources :subscriptions
  resources :plans
  resources :pages
  #mount Resque::Server.new, :at => '/resque' if Rails.env.production?

  mount Tolk::Engine => '/tolk', :as => 'tolk'

  devise_for :users, controllers: {
    sessions: "sessions",
    invitations:"users/invitations",
    registrations: "registrations",
    passwords: "passwords",
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  #mount Monologue::Engine, at: '/blog'

  resources :categories

  match '/groups/suggest_user' => 'groups#suggest_user'

  match '/users/eula' => 'users#eula'

  match "/about/rules" => redirect("/pages/2")
  match "/about/faq" => redirect("/pages/2")

  match '/ideas/flag/:id' => 'ideas#flag'
  match '/ideas/abusive/:id' => 'ideas#abusive'
  match '/ideas/not_abusive/:id' => 'ideas#not_abusive'
  match '/admin/all_flagged' => 'admin#all_flagged'
  match '/admin/statistics' => 'admin#statistics'
  match '/admin/all_deleted' => 'admin#all_deleted'
  match '/users/list_suspended' => 'users#list_suspended'
  match '/users/additional_information' => 'users#additional_information'
  match '/users/destroy_from_admin' => 'users#destroy_from_admin'

  match '/subscription_accounts/select_plan' => 'subscription_accounts#select_plan'
  match 'authenticate_from_island_is' =>'users#authenticate_from_island_is'
  match '/sub_instances/setup_status' =>'sub_instances#setup_status'

  resources :subscription_accounts do
    collection do
      get :users
      get :about
    end
  end

  resources :groups

  resources :sub_instances do
    member do
      get :email
      get :picture
      put :picture_save
    end
  end

  resources :users do
  	resource :profile
  	collection do
  	  get :endorsements
  	  post :order
  	end
  	member do
  	  put :suspend
      put :unsuspend
      get :activities
      get :comments
  	  get :points
  	  get :discussions
  	  get :capital
  	  put :impersonate
  	  get :followers
  	  get :documents
  	  get :stratml
  	  get :ignorers
  	  get :following
  	  get :ignoring
  	  post :follow
  	  post :unfollow
  	  get :make_admin
      get :unmake_admin
  	  get :ads
  	  get :ideas
  	  get :signups
  	  post :endorse
  	  get :resend_activation
    end
    resources :messages
    resources :followings do
      collection do
        put :multiple
      end
    end
    resources :user_contacts, :as => "contacts" do
      collection do
        put :multiple
        get :following
        get :members
        get :not_invited
        get :invited
      end
    end
  end

  resources :settings do
    collection do
      get :signups
      get :picture
      put :picture_save
      get :legislators
      post :legislators_save
      get :delete
    end
  end

  resources :ideas do
  	member do
      get :statistics
      put :flag_inappropriate
      get :flag
      put :bury
      put :compromised
      put :successful
      put :failed
      put :intheworks
      post :endorse
      get :endorsed
      get :opposed
      get :activities
      get :endorsers
      get :opposers
      get :discussions
      put :create_short_url
      post :tag
      put :tag_save
      get :points
      get :opposer_points
      get :endorser_points
      get :neutral_points
      get :everyone_points
      get :top_points
      get :idea_detail
      get :endorsed_points
      get :opposed_top_points
      get :endorsed_top_points
      get :comments
      get :documents
      get :update_status
      get :move
      post :move
      get :change_category
      put :change_category
  	end
  	collection do
      get :yours
      get :yours_finished
      get :yours_top
      get :yours_ads
      get :yours_lowest
      get :yours_created
      get :network
      get :consider
      get :finished
      get :finished_in_progress
      get :finished_successful
      get :finished_failed
      get :finished_compromised
      get :ads
      get :top
      get :by_tag
      get :by_impressions
      get :most_discussed
      get :all_tags
      get :top_24hr
      get :top_7days
      get :top_30days
      get :rising
      get :falling
      get :controversial
      get :random
      get :newest
      get :untagged
      get :revised
  	end
    resources :changes do
      member do
        put :start
        put :stop
        put :approve
        put :flip
        get :activities
      end
      resources :votes
    end
    resources :idea_revisions do
      member do
        get :clean
      end
    end
    resources :points
    resources :ads do
      collection do
        post :preview
      end
      member do
        post :skip
      end
    end
  end

  resources :activities do
    member do
      put :undelete
      get :unhide
    end
    resources :following_discussions, :as=>"followings"
    resources :comments do
      collection do
        get :more
      end
      member do
        get :unhide
        get :flag
        post :not_abusive
        post :abusive
      end
    end
  end

  resources :points do
    member do
      get :flag
      post :not_abusive
      post :abusive
      get :activity
      get :discussions
      post :quality
      post :unquality
      get :unhide
    end
    collection do
      get :newest
      get :revised
      get :your_ideas
      get :your_index
    end
    resources :revisions do
      member do
        get :clean
      end
    end
  end

  resources :color_schemes do
    collection do
      put :preview
    end
  end

  resources :instances do
    member do
      get :apis
    end
  end

  resources :widgets do
    collection do
      get :ideas
      get :discussions
      get :points
      get :preview_iframe
      post :preview
    end
  end

  resources :bulletins do
    member do
      post :add_inline
    end
  end

  resources :searches do
    collection do
      get :all
    end
  end

  resources :signups
  resources :endorsements
  resources :unsubscribes
  resources :notifications
  resources :about
  resources :tags
  resources :delayed_jobs do
    member do
      get :top
      get :clear
    end
  end

  resource :open_id

  if ENV['YRPRI_SET_HOME_TO_WORLD']
    match '/' => 'home#world'
  else
    match '/' => 'home#index'
  end
  match '/unsubscribe' => 'unsubscribes#new', :as => :unsubscribe
  match '/yours' => 'ideas#yours'
  match '/hot' => 'ideas#hot'
  match '/cold' => 'ideas#cold'
  match '/new' => 'ideas#new'
  match '/controversial' => 'ideas#controversial'
  match '/vote/:action/:code' => 'vote#index'
  match '/welcome' => 'home#index'
  match '/search' => 'searches#index'
  match '/splash' => 'splash#index'
  match '/issues' => 'issues#index'
  match '/issues.:format' => 'issues#index'
  match '/issues/:id' => 'issues#show', as: 'issue'
  match '/issues/:id.:format' => 'issues#show'
  match '/issues/:id/:action' => 'issues#index'
  match '/issues/:id/:action.:format' => 'issues#index'
  match '/pictures/:short_name/:action/:id' => 'pictures#index'
  match ':controller' => '#index'
  match ':controller/:action' => '#index'
  match ':controller/:action.:format' => '#index'
  match '/:controller(/:action(/:id))'
  match ':redirect' => redirect("/404.html"), :as => :catchall , :constraints => { :redirect => /.*/i }
end
  # The idea is based upon order of creation:
  # first created -> highest idea.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :active, :last_payment_at, :paymill_id, :email, :plan_id, :user_id, :paymill_card_token

  belongs_to :plan
  belongs_to :user
  validates_presence_of :plan_id
  
  attr_accessor :paymill_card_token


  def next_charge_date
    if self.paymill_id
      subscription = Paymill::Subscription.find(self.paymill_id)
      Rails.logger.info("Next charge date #{subscription.next_capture_at}")
      subscription.next_capture_at.strftime("%d %B %Y")
    end
  end

  def cancel_current_subscription(current_subscription)
    Rails.logger.info("Cancel current subscription #{current_subscription} #{current_subscription.paymill_id}")
    if current_subscription.paymill_id
      Paymill::Subscription.delete(current_subscription.paymill_id)
      current_subscription.paymill_id = nil
      current_subscription.save(:validate=>false)
    end
  end

  def save_with_payment(user,current_subscription)
    if valid?
      if user.paymill_id
        client = Paymill::Client.find(user.paymill_id)
      else
        client = Paymill::Client.create email: user.email, description: user.login
        user.paymill_id = client.id
        user.save(:validate=>false)
      end
      payment = Paymill::Payment.create token: paymill_card_token, client: client.id
      cancel_current_subscription(current_subscription)
      subscription = Paymill::Subscription.create offer: plan.paymill_offer_id, client: client.id, payment: payment.id
      self.user=user
      self.paymill_id = subscription.id
      save!
      offer = Paymill::Offer.find(plan.paymill_offer_id)
      UserMailer.thank_you_for_payment(user,"#{offer.currency} #{offer.amount/100.0}",plan,subscription.next_capture_at.strftime("%d %B %Y")).deliver
    end
  rescue Paymill::PaymillError => e
    Rails.logger.error "Paymill error while creating customer: #{e.message} #{Paymill.api_key}"
    errors.add :base, tr("There was a problem with your credit card - Please try again.","here")
    false
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :authenticate_root!, :only => [:index, :destroy ]

  def get_layout
    return Instance.current.layout_for_subscriptions
  end

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscriptions }
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
   plan = Plan.find(params[:plan_id]) 
   @subscription = plan.subscriptions.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(params[:subscription])
    @subscription.account_id = SubInstance.current.account_id
    respond_to do |format|
      if @subscription.plan.amount > 0.0
        result = @subscription.save_with_payment(current_user,@current_subscription)
      else
        @subscription.cancel_current_subscription(@current_subscription) if @current_subscription
        result = @subscription.save
      end
      if result
        @subscription.active = true
        @subscription.save
        sub_instance = SubInstance.current
        sub_instance.reload
        sub_instance.subscription_id = @subscription.id
        sub_instance.save!
        format.html { redirect_to "/subscription_accounts/users", notice: tr("Subscription was successfully created.","here") }
        format.json { render json: @subscription, status: :created, location: @subscription }
      else
        format.html { render action: "new" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_plan
    @subscription = Subscription.find(params[:id])
    @plan = Plan.find(params[:plan_id])
    if @subscription.plan.id != @plan.id
      @subscription.plan = @plan
      if @plan.amount>0.0
        @subscription.active = false
      else
        @subscription.cancel_current_subscription(@current_subscription) if @current_subscription
        @subscription.active = true
      end
    end
    respond_to do |format|
      if @plan.amount>0.0
        format.html { redirect_to :action=>"new", :plan_id=>@plan.id }
      elsif @subscription.save
        format.html { redirect_to SubInstance.current.show_url, :notice=> tr("Subscription was successfully update.","here") }
        format.json { render json: @subscription, status: :created, location: @subscription }
      else
        format.html { redirect_to SubInstance.current.show_url, error: tr("Subscription could not be updated.","here") }
        format.json { render json: @subscription, status: :error, location: @subscription }
      end
    end
  end

    # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end
end

app/views/subscriptions/_form.html.haml
= form_for @subscription do |f|
  - if @subscription.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscription.errors.count, "error")} prohibited this subscription from being saved:"
      %ul
        - @subscription.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :paymill_id
    = f.text_field :paymill_id
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :plan_id
    = f.number_field :plan_id
  .field
    = f.label :last_payment_at
    = f.datetime_select :last_payment_at
  .field
    = f.label :active
    = f.check_box :active
  .actions
    = f.submit 'Save'

app/views/subscriptions/edit.html.haml
%h1 Editing subscription

= render 'form'

= link_to 'Show', @subscription
\|
= link_to 'Back', subscriptions_path

app/views/subscriptions/index.html.haml
%h1 Listing subscriptions

%table
  %tr
    %th Paymill
    %th User
    %th Plan
    %th Last payment at
    %th Active
    %th
    %th
    %th

  - @subscriptions.each do |subscription|
    %tr
      %td= subscription.paymill_id
      %td= subscription.user_id
      %td= subscription.plan_id
      %td= subscription.last_payment_at
      %td= subscription.active
      %td= link_to 'Show', subscription
      %td= link_to 'Edit', edit_subscription_path(subscription)
      %td= link_to 'Destroy', subscription, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subscription', new_subscription_path

app/views/subscriptions/new.html.haml
.row
  .large-12.columns
    .panel
      %h1
        - if @current_subscription and @current_subscription.active
          = tr("Updating subscription","here")
        - else
          = tr("Creating subscription","here")
      .panel
        %p
          - if @subscription.plan.private_instance
            = tr("You are subscribing to a private plan with email invites for up to {number_of_users} users.","here",:number_of_users=>@subscription.plan.max_users)
          - else
            = tr("You are subscribing to a public plan with open registration including Facebook for up to {number_of_users} users.","here",:number_of_users=>@subscription.plan.max_users)
        .row
          .large-5.columns
            %p
              %h4
                = tr("Name of your instance","here")
              = current_sub_instance.name
            %p
              %h4
                = tr("Domain name","here")
              = current_sub_instance.show_url
            %p
              %h4
                = tr("Full name","here")
              = current_user.login
            %p
              %h4
                = tr("Email","here")
              = current_user.email
          .large-7.columns
            %p
              %h4
                = tr("Your payment information","here")
              = form_for @subscription do |f|
                - if @subscription.errors.any?
                  .error_messages
                    %h2
                      = pluralize(@subscription.errors.count, tr("error","here"))
                      prohibited this subscription from being saved:
                    %ul
                      - @subscription.errors.full_messages.each do |msg|
                        %li= msg
                = f.hidden_field :plan_id
                = f.hidden_field :paymill_card_token
                = f.hidden_field :currency, :value=>@currency_code
                = f.hidden_field :amount, :value=>@subscription.plan.amount

                - if @subscription.plan.amount>0.0
                  - if @subscription.paymill_card_token.present?
                    = tr("Credit card has been provided already you can just click on subscribe.","here")
                  - else
                    .row
                      .large-12.columns
                        %p
                          - if @subscription.plan.vat>0.0
                            = tr("{amount} per month including vat","here",:amount=>currency_with_unit(@subscription.plan.amount_with_vat, @subscription.plan.currency))
                          - else
                            = tr("{amount} per month","here",:amount=>currency_with_unit(@subscription.plan.amount_with_vat, @subscription.plan.currency))
                    .row
                      .large-6.columns
                        .field
                          = label_tag :card_number, tr("Cardholder name","here")
                          = text_field_tag :cardholder, nil, name: nil
                      .large-6.columns
                        .field
                          = label_tag :card_number, tr("Credit Card Number","here")
                          = text_field_tag :card_number, nil, name: nil
                    .row
                      .large-5.columns
                        .field
                          = label_tag :card_code, tr("Security Code (CVV)","here")
                          = text_field_tag :card_code, nil, name: nil
                      .large-4.columns
                        .field
                          = label_tag :card_month, tr("Expiry month","here")
                          = select_month nil, {:add_month_numbers=> true}, {:name=> nil, :id=> "card_month"}
                      .large-3.columns
                        .field
                          = label_tag :card_month, tr("Expiry year","here")
                          = select_year nil, {:start_year=> Date.today.year, :end_year=> Date.today.year+15}, {:name=> nil, :id=> "card_year"}
                %h2
                  #paymill_error{:style=>"color:#F00;"}
                    %noscript JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
                %br
                %center
                  = f.submit tr("Subscribe now","here"), :id=>"submit_button", :class=>"button"
        %p
          %b
            = tr("Your subscription will be effective immediately.","here")
            = tr("Your first monthly payment will be {amount} charged now.","here",:amount=>currency_with_unit(@subscription.plan.amount_with_vat, @subscription.plan.currency))
            = tr("You can cancel your subscription at any time.","here")

        = link_to tr("Select another subscription plan","here"), "/subscription_accounts/select_plan"

app/views/subscriptions/show.html.haml
%p#notice= notice

%p
  %b Paymill:
  = @subscription.paymill_id
%p
  %b User:
  = @subscription.user_id
%p
  %b Plan:
  = @subscription.plan_id
%p
  %b Last payment at:
  = @subscription.last_payment_at
%p
  %b Active:
  = @subscription.active

= link_to 'Edit', edit_subscription_path(@subscription)
\|
= link_to 'Back', subscriptions_path